dist: xenial
language: ruby
rvm:
- 2.6.0
env:
- JEKYLL_ENV=production
cache:
  bundler: true
  directories:
  - "$TRAVIS_BUILD_DIR/.jekyll-cache"
branches:
  only: develop
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key
- ssh-add /tmp/deploy_key
deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    branch:
    - develop
before_install:
- openssl aes-256-cbc -K $encrypted_1853e33ef5a2_key -iv $encrypted_1853e33ef5a2_iv
  -in id_rsa.enc -out /tmp/deploy_key -d
