language: node_js
node_js:
- '11'
cache: npm
install:
- npm install
script:
- npm run build
before_deploy:
- openssl aes-256-cbc -K $encrypted_98a2fa371a1b_key -iv $encrypted_98a2fa371a1b_iv
  -in deploy_key.enc -out /tmp/deploy_key -d
- eval "$(ssh-agent -s)" 
- ssh-add /tmp/deploy_key
