language: node_js
node_js:
- '11'
cache: npm
install:
- npm install
script:
- npm run build
before_deploy:
- openssl aes-256-cbc -K $encrypted_98a2fa371a1b_key -iv $encrypted_98a2fa371a1b_iv
  -in deploy_key.enc -out /tmp/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key
- ssh-add /tmp/deploy_key
deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    branch:
    - develop
before_install:
- openssl aes-256-cbc -K $encrypted_98a2fa371a1b_key -iv $encrypted_98a2fa371a1b_iv
  -in deploy_key.enc -out deploy_key -d
