# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bhuvy's Blog
email: bvenkat2@illinois.edu
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://bhuvy2.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bhuvy2
github_username: bhuvy2

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
collections:
  posts:
    output: true
    permalink: /blog/:path
  livepages:
    output: true
    permalink: /:path
reveal:
  css_url: 'https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.7.0/css/reveal.css'
  css_theme_url: 'https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.7.0/css/theme/black.css'
  css_syntax_url: '/css/reveal-code-style.css'
  lib_head_url: 'https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.7.0/lib/js/head.min.js'
  reveal_js_url: 'https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.7.0/js/reveal.js'
plugins_dir:
  - _plugins
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
